# -- [Application Configuration] -- #
server:
    servlet:
        context-path: /code-guard
    port: 8080
spring:
    application:
        name: CodeGuard

# -- [DDBB Configuration] -- #
    users:
        datasource:
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:users
            username: users
            password:
    deletedUsers:
        datasource:
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:deletedUsers
            username: deletedUsers
            password:
    password:
        datasource:
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:password
            username: password
            password:
    exercises:
        datasource:
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:exercises
            username: exercises
            password:
    h2:
        console:
            enabled: true
            path: /h2-console

# -- [JPA Configuration] -- #
    main:
        allow-bean-definition-overriding: true
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create

# -- [Swagger] -- #
springdoc:
    api-docs:
        path: /api
    swagger-ui:
        path: api/index.html
        enabled: true
